services:
  - type: web
    name: hill-country-website
    env: node
    plan: free
    buildCommand: npm install && npx vite build && npx esbuild server/production.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/server.js && cp -r attached_assets dist/
    startCommand: NODE_ENV=production node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
    healthCheckPath: /health